print_info() {
    prin "$(color 6)        .-."
    prin "$(color 6)       |o_o|"
    prin "$(color 6)       |:_/|"
    prin "$(color 6)      //   \\ \\"
    prin "$(color 6)     (|     | )"
    prin "$(color 6)    /'\\_   _/'\\"
    prin "$(color 6)    \\___)=(___/"
    prin ""
    info "$(color 6)  OS       " distro
    info "$(color 6)  Kernel   " kernel
    info "$(color 6)  Uptime   " uptime
    info "$(color 6)  Shell    " shell
    info "$(color 6)  DE       " de
    info "$(color 6)  Terminal " term
    info "$(color 6)  CPU      " cpu
    info "$(color 6)  GPU      " gpu
    info "$(color 6)  Memory   " memory
    info "$(color 6)  Disk     " disk
    prin ""
    prin "$(color 6)  ORIZON Linux Beta 2"
    prin "$(color 6)  taplink.cc/orizon"
    prin ""
    prin "$(color 1) ● $(color 2) ● $(color 3) ● $(color 4) ● $(color 5) ● $(color 6) ●"
}

kernel_shorthand="on"
distro_shorthand="off"
os_arch="on"
uptime_shorthand="on"
memory_percent="on"
memory_unit="gib"
package_managers="on"
shell_path="off"
shell_version="on"
cpu_brand="on"
cpu_speed="on"
cpu_cores="logical"
cpu_temp="C"
gpu_brand="on"
gpu_type="all"
refresh_rate="on"
gtk_shorthand="on"
colors=(4 6 4 6 4 6)
bold="on"
underline_enabled="on"
underline_char="-"
separator=" ➜"
color_blocks="on"
block_range=(0 15)
block_width=3
block_height=1
image_backend="ascii"
ascii_distro="Ubuntu"
ascii_colors=(4 6 4 6 4 6)
ascii_bold="on"
stdout="off"
