name: Lint Shell Scripts

on: [push, pull_request]

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run non-strict ShellCheck Action
        uses: ludeeus/action-shellcheck@master
        with:
          sc_args: "--fail-level=error"
